package org.zoxweb.shared.data;

import org.zoxweb.shared.security.shiro.ShiroDAO;
import org.zoxweb.shared.util.DeviceID;
import org.zoxweb.shared.util.GetNVConfig;

import org.zoxweb.shared.util.NVConfig;
import org.zoxweb.shared.util.NVConfigEntity;
import org.zoxweb.shared.util.NVConfigEntityLocal;
import org.zoxweb.shared.util.NVConfigManager;
import org.zoxweb.shared.util.SharedStringUtil;
import org.zoxweb.shared.util.SharedUtil;
import org.zoxweb.shared.util.SubjectID;

@SuppressWarnings("serial")
public class DeviceDAO
	extends PropertyDAO
	implements DeviceID<String>, SubjectID<String>
{

	public enum Param
	    implements GetNVConfig
	{
		DEVICE_ID(NVConfigManager.createNVConfig("device_id", "Device identifier generated by the app system.", "DeviceID", true, false, String.class)),
		SUBJECT_ID(NVConfigManager.createNVConfig("subject_id", "Device subject id", "SubjectID", true, false, true, String.class, null)),
        MODEL(NVConfigManager.createNVConfig("model", "The name of the device's model or product.", "Model", false, false, String.class)),
        PLATFORM(NVConfigManager.createNVConfig("platform", "The device's operating system name.", "Platform", false, false, String.class)),
        VERSION(NVConfigManager.createNVConfig("version", "The operating system version.", "Version", false, false, String.class)),
        MANUFACTURER(NVConfigManager.createNVConfig("manufacturer", "The device's manufacturer.", "Manufacturer", false, false, String.class)),
        VIRTUAL(NVConfigManager.createNVConfig("virtual", "Whether the device is running on a simulator.", "Virtual", false, false, boolean.class)),
        SERIAL_NUMBER(NVConfigManager.createNVConfig("serial_number", "The device hardware serial number.", "SerialNumber", false, false, String.class)),
		
		;
	
	    private final NVConfig nvc;
	
	    Param(NVConfig nvc)
	    {
	        this.nvc = nvc;
	    }
	
	    public NVConfig getNVConfig()
	    {
	        return nvc;
	    }
	}

	public static final NVConfigEntity NVC_DEVICE_DAO = new NVConfigEntityLocal(
											            "device_dao",
											            null ,
											            null,
											            true,
											            false,
											            false,
											            false,
											            DeviceDAO.class,
											            SharedUtil.extractNVConfigs(Param.values()),
											            null,
											            false,
											            PropertyDAO.NVC_PROPERTY_DAO);
	
	
	public DeviceDAO()
    {
		super(NVC_DEVICE_DAO);
	}

    /**
     * Returns the device ID generated by the app system.
     * @return the device id
     */
    @Override
	public String getDeviceID()
    {
		return lookupValue(Param.DEVICE_ID);
	}

    /**
     * Sets the device ID generated by the app system.
     * @param id of the device
     */
	@Override
	public void setDeviceID(String id)
    {
		setValue(Param.DEVICE_ID, id);
	}

    /**
     * Returns the name of the device's model or product. Retrieved from the device.
     * @return the model of device
     */
    public String getModel()
    {
        return lookupValue(Param.MODEL);
    }

    /**
     * Sets the name of the device's model or product. Retrieved from the device.
     * @param model of the device
     */
    public void setModel(String model)
    {
        setValue(Param.MODEL, model);
    }

    /**
     * Returns the device's operating system name. Retrieved from the device.
     * @return the platform
     */
    public String getPlatform()
    {
        return lookupValue(Param.PLATFORM);
    }

    /**
     * Sets the device's operating system name. Retrieved from the device.
     * @param platform platform
     */
    public void setPlatform(String platform)
    {
        setValue(Param.PLATFORM, platform);
    }

    /**
     * Returns the operating system version. Retrieved from the device.
     * @return version
     */
    public String getVersion()
    {
        return lookupValue(Param.VERSION);
    }

    /**
     * Sets the operating system version. Retrieved from the device.
     * @param version of the device
     */
    public void setVersion(String version)
    {
        setValue(Param.VERSION, version);
    }

    /**
     * Returns the device's manufacturer. Retrieved from the device.
     * @return
     */
    public String getManufacturer()
    {
        return lookupValue(Param.MANUFACTURER);
    }

    /**
     * Sets the device's manufacturer. Retrieved from the device.
     * @param manufacturer
     */
    public void setManufacturer(String manufacturer)
    {
        setValue(Param.MANUFACTURER, manufacturer);
    }

    /**
     * Returns whether the device is running on a simulator. Retrieved from the device.
     * @return
     */
    public boolean isVirtual()
    {
        return lookupValue(Param.VIRTUAL);
    }

    /**
     * Sets whether the device is running on a simulator. Retrieved from the device.
     * @param virtual
     */
    public void setVirtual(boolean virtual)
    {
        setValue(Param.VIRTUAL, virtual);
    }

    /**
     * Returns the device hardware serial number. Retrieved from the device.
     * @return
     */
    public String getSerialNumber()
    {
        return lookupValue(Param.SERIAL_NUMBER);
    }

    /**
     * Sets the device hardware serial number. Retrieved from the device.
     * @param serialNumber
     */
    public void setSerialNumber(String serialNumber)
    {
        setValue(Param.SERIAL_NUMBER, serialNumber);
    }


    /**
     * Sets the additional device properties.
     * @param properties
     */
//    public synchronized void setProperties(ArrayValues<GetNameValue<String>> properties)
//    {
//        getProperties().add(properties.values(), true);
//    }

	@Override
	public synchronized String getSubjectID() 
	{
		String subID = lookupValue(Param.SUBJECT_ID);
		if (subID == null)
		{
			if (!SharedStringUtil.isEmpty(getManufacturer()))
				subID = SharedUtil.toCanonicalID(ShiroDAO.CAN_ID_SEP, getManufacturer(), getModel(), getVersion(), getSerialNumber(), getDeviceID());
			else
				subID = SharedUtil.toCanonicalID(ShiroDAO.CAN_ID_SEP, getModel(), getVersion(), getSerialNumber(), getDeviceID());
				
			setValue(Param.SUBJECT_ID, subID);
		}
		// TODO Auto-generated method stub
		return subID;
	}

	
	@Deprecated
    public void setSubjectID(String subjectID)
            throws UnsupportedOperationException
    {
        throw new UnsupportedOperationException("Not supported.");
    }

}